# SITE CONFIGURATION
baseurl: ""
url: ""

defaults:
  - scope:
      path: "" # an empty string here means all files in the project
    values:
      image: /assets/img/shx_square.jpg # seo tag
  - scope:
      path: "_pages"
    values:
      layout: page

collections:
  pages:
    output: true
    permalink: /:name/
  core:
    output: true
    permalink: /:name/

# THEME-SPECIFIC CONFIGURATION
theme_settings:
  # Scripts / Features
  google_analytics: # Tracking ID, e.g. "UA-000000-01"
  disqus_shortname:
  katex: true # Enable if using math markup

  # Localization strings
  str_follow_on: "Follow on"
  str_rss_follow: "Follow RSS feed"
  str_share_on: "Share on"
  str_add_to: "Add to"
  str_email: "Email"
  str_tweet: "Tweet"
  str_pin_it: "Pin it"
  str_next_post: "Next post"
  str_previous_post: "Previous post"
  str_next_page: "Next"
  str_previous_page: "Prev"
  str_javascript_required_disqus: "Please enable JavaScript to view comments."

  # Post navigation
  post_navigation: true

  # Colours, typography and padding
  # Open the "_sass > base" folder, and open "_variables.scss"

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: :compressed
plugins:
plugins:
  - jekyll-seo-tag
exclude:
  - ".gitignore"
  - "_site"
  - ".jekyll-cache"
  - "Gemfile"
  - "Gemfile.lock"
  - "LICENSE"
  - "README.md"
