# SITE CONFIGURATION
baseurl: ""
url: ""

defaults:
  - scope:
      path: "" # an empty string here means all files in the project
    values:
      image: /assets/img/shx_square.jpg # seo tag
  - scope:
      path: "_pages"
    values:
      layout: page

collections:
  pages:
    output: true
    permalink: /:name/
  core:
    output: true
    permalink: /:name/

# enable netlify cms
netlify_cms: true

# THEME-SPECIFIC CONFIGURATION
theme_settings:
  # Scripts / Features
  google_analytics: # Tracking ID, e.g. "UA-000000-01"

  # Colours, typography and padding
  # Open the "_sass > base" folder, and open "_variables.scss"

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: :compressed
plugins:
plugins:
  - jekyll-seo-tag
exclude:
  - ".gitignore"
  - "_site"
  - ".jekyll-cache"
  - "Gemfile"
  - "Gemfile.lock"
  - "LICENSE"
  - "README.md"
