backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
  repo: cmu-lib/shakespeare-vr
media_folder: "assets/images"
collections:
  - name: page
    label: "Page"
    description: "A page on the site"
    folder: "_pages"
    create: true
    fields:
      - name: title
        label: Title
        widget: string
      - name: feature-img
        label: Banner Image
        widget: image
        required: false
      - name: body
        label: Content
        widget: markdown
      - name: hide
        label: Hide from navigation
        widget: boolean
        default: false
        hint: Check this to hide this page from the main navigation bar
        required: false
      - name: layout
        label: Layout
        widget: hidden
        default: page
  - name: home
    label: "Home"
    files:
      - label: Home Page
        name: home
        file: "index.md"
        fields:
          - name: title
            label: Title
            widget: string
          - name: body
            label: Content
            widget: markdown
          - name: layout
            label: Layout
            widget: hidden
            default: home
          - name: hide
            label: hide
            widget: hidden
            default: true
    create: false
    delete: false
    fields:
      - name: title
        label: Title
        widget: string
      - name: body
        label: Content
        widget: markdown
      - name: layout
        label: Layout
        widget: hidden
        default: home
  - name: settings
    label: "Site Settings"
    create: false
    delete: false
    files:
      - label: Main Settings
        name: main
        file: "_data/variables.yml"
        fields:
          - name: footer_text
            label: Footer Text
            hint: This HTML will be displayed in the footer of the site on every page.
            widget: markdown


