---
---
backend:
  name: git-gateway
  repo: cmu-lib/shakespeare-vr
  site_domain: cms.netlify.com
media_folder: "assets/img"
public_folder: "{{ 'assets/img' | relative_url }}"
site_url: https://cmu-shx-vr.netlify.com
display_url: https://cmu-shx-vr.netlify.com
collections:
  - name: page
    label: "Page"
    description: "Add, delete, and edit pages on the site."
    folder: "_pages"
    create: true
    fields:
      - name: title
        label: Title
        widget: string
      - name: subtitle
        label: Subtitle
        widget: string
        required: false
      - name: feature-img
        label: Banner Image
        widget: image
        hint: Ideal size is 1425 x 600 px
        default: /assets/img/shx_banner.jpg
      - name: body
        label: Content
        widget: markdown
      - name: layout
        label: Layout
        widget: hidden
        default: page
  - name: home
    label: "Home"
    create: false
    delete: false
    files:
      - label: Home Page
        name: home
        file: "index.md"
        fields:
          - name: title
            label: Title
            widget: string
          - name: subtitle
            label: Subtitle
            widget: string
            required: false
          - name: feature-img
            label: Banner Image
            hint: Ideal size is 1425 x 600 px
            widget: image
            required: false
          - name: body
            label: Content
            widget: markdown
          - name: layout
            label: Layout
            widget: hidden
            default: home
  - name: settings
    label: "Site Settings"
    create: false
    delete: false
    description: Modify site-wide settings
    editor:
      preview: false
    files:
      - label: Main Settings
        name: main
        file: "_data/variables.yml"
        fields:
          - name: title
            label: Site Title
            hint: This will appear in the nav bar on the upper left and in the browser tab
            widget: string
          - name: subtitle
            label: Site Subtitle
            hint: This will appear in the nav bar on the upper left under the site title
            widget: string
          - name: footer_text
            label: Footer Text
            hint: This HTML will be displayed in the footer of the site on every page.
            widget: markdown
          - name: avatar
            label: Avatar
            hint: Logo image to appear in the upper left hand corner. Must be square.
            widget: image
          - name: favicon
            label: Favicon
            hint: Select an image to appear in tabs and bookmarks
            widget: image
            pattern: [".+\\.ico$", "Must have extension .ico"]
      - label: Navigation Menu
        name: nav
        file: "_data/navlinks.yml"
        fields:
          - name: page_ordering
            label: Page ordering
            widget: relation
            collection: page
            valueField: title
            multiple: true
            searchFields:
              - title
            hint: Select pages from the dropdown in the order that they should appear on the navigation bar.
