backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
  repo: cmu-lib/shakespeare-vr
media_folder: "assets/images"
collections:
  - name: page
    label: "Page"
    description: "A page on the site"
    folder: "pages"
    create: true
    fields:
      - name: title
        title: Title
        widget: string
      - name: feature-img
        title: Banner Image
        widget: image
      - name: body
        title: Content
        widget: markdown
      - name: hide
        title: Hide from navigation
        widget: boolean
        default: false
        hint: Check this to hide this page from the main navigation bar
        required: false
      - name: layout
        title: Layout
        widget: hidden
        default: page
  - name: home
    label: "Home"
    files:
      - label: Home Page
        name: home
        file: "index.md"
        fields:
          - name: title
            title: Title
            widget: string
          - name: body
            title: Content
            widget: markdown
          - name: layout
            title: Layout
            widget: hidden
            default: home
          - name: hide
            title: hide
            widget: hidden
            default: true
    create: false
    delete: false
    fields:
      - name: title
        title: Title
        widget: string
      - name: body
        title: Content
        widget: markdown
      - name: layout
        title: Layout
        widget: hidden
        default: home
